### ISSUE TITLE
内网穿透服务器插件连接mirai报错

### ISSUE THREAD

**Issue by 1zyao** [MakesYT/chatsync_mirai#1]
mirai报错：
2023-05-07 00:01:10 W/stderr: java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.contact.Group.sendMessage(net.mamoe.mirai.message.data.Message)" because the return value of "net.mamoe.mirai.Bot.getGroup(long)" is null
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//top.ncserver.chatsync.V2.MsgTools.QQsendMsgMessageChain(MsgTools.java:325)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//top.ncserver.Chatsync$1.stateEvent0(Chatsync.java:100)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.extension.processor.AbstractMessageProcessor.stateEvent(AbstractMessageProcessor.java:102)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.transport.TcpAioSession.<init>(TcpAioSession.java:165)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.transport.AioQuickServer.createSession(AioQuickServer.java:201)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.transport.AioQuickServer.access$300(AioQuickServer.java:54)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.transport.AioQuickServer$2.completed(AioQuickServer.java:175)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.transport.AioQuickServer$2.completed(AioQuickServer.java:165)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.enhance.EnhanceAsynchronousServerSocketChannel.doAccept(EnhanceAsynchronousServerSocketChannel.java:104)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.enhance.EnhanceAsynchronousChannelGroup.lambda$new$2(EnhanceAsynchronousChannelGroup.java:121)
2023-05-07 00:01:10 W/stderr: 	at chatsync-1.0.6.mirai.jar//org.smartboot.socket.enhance.EnhanceAsynchronousChannelGroup$Worker.run(EnhanceAsynchronousChannelGroup.java:294)
2023-05-07 00:01:10 W/stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-07 00:01:10 W/stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-07 00:01:10 W/stderr: 	at java.base/java.lang.Thread.run(Thread.java:833)

服务端一直显示
[06:36:08 INFO]: [chatsync] 连接成功
[06:36:08 WARN]: [chatsync] 连接丢失

服务端java：
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

miraijava：OpenJDK 64-Bit Server VM 17.0.6 (arch: 64)

**Comment by Maklith** [comment]
检查一下群号的设置，查看配置文件config/top...

**Comment by 1zyao** [comment]
群号不对 现在好了 谢谢
